language: node_js
node_js:
  - "9"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=test PORT=3000
cache:
  directories:
    - node_modules
    - frontend/node_modules
install:
  - npm install
  - npm run build

jobs:
  include:
    - stage: test
      script:
        - nohup npm run start &
        - sleep 3
        - npm run test
    - stage: deploy
      ixf: branch = master
      script: ./deploy